tokens:
  slack_token: your bot's Slack API token

cafe_name: cafe-name

whitelist_channels:
  - Channel
  - IDs
  - Go
  - Here

guy_fieri_images:
  - https://media.comicbook.com/2019/12/guy-fieri-baby-yoda-meme-1198350-1280x0.jpeg
  - http://vignette2.wikia.nocookie.net/universe-of-smash-bros-lawl/images/a/a3/Guy_Fieri.png
  - https://www.borderstan.com/files/2015/10/guyfieri-0179-pkg_resized.jpg
  - http://food.fnr.sndimg.com/content/dam/images/food/editorial/talent/guy-fieri/FN-TalentAvatar-Guy-Fieri-800x800.jpg.rend.hgtvcom.616.616.jpeg
  - https://vignette1.wikia.nocookie.net/playstationallstarsfanfictionroyale/images/7/72/Guy-fieri-.jpg/revision/latest?cb=20150618032144
  - http://cimg.tvgcdn.net/i/r/2012/11/19/cb2b6267-70f1-4fe7-b8ab-a828b599b69f/crop/660x494+0+0/thumbnail/350x262/3abbde35b61b93394a7bc6d010f48342/121119guy-fieri1.jpg
  - http://www.foodandwine.com/fwx/sites/default/files/fwx-kitchen-trash-guy-fieri.jpg
  - http://static4.businessinsider.com/image/4fb12ce269bedd0305000002/look-at-what-happens-when-food-network-host-guy-fieri-eats-at-a-restaurant-for-his-show.jpg
  - https://slack-imgs.com/?c=1&o1=ro&url=https%3A%2F%2Fpbs.twimg.com%2Fmedia%2FDZP3qbGVwAElaw_.jpg

guy_fieri_phrases:
  - off the hook
  - like a game of blackjack at the Flavortown casino
  - bomb-dot-com tasty
  - dynamite
  - gangster
  - lights-out delicious
  - the real deal
  - bananas, and bananas is good
  - winner winner flavorful dinner

bot_user:
  id: bot ID
  name: bot's name
  tag_formatted_id: <@bot ID>